In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Reading the data file in df

**Read the csv data file and disply its head**

In [ ]:
# Code here please
df=pd.read_csv('/content/mammographic_masses_data_clean.csv')
df.head()

   BI-RADS  Age  Shape  Margin  Density  Target
0        5   67      3       5        3       1
1        5   58      4       5        3       1
2        4   28      1       1        3       0
3        5   57      1       5        3       1
4        5   76      1       4        3       1

   BI-RADS  Age  Shape  Margin  Density  Target
0        5   67      3       5        3       1
1        5   58      4       5        3       1
2        4   28      1       1        3       0
3        5   57      1       5        3       1
4        5   76      1       4        3       1

**How many data entries you have?**

In [ ]:
# Code here please
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   BI-RADS  830 non-null    int64
 1   Age      830 non-null    int64
 2   Shape    830 non-null    int64
 3   Margin   830 non-null    int64
 4   Density  830 non-null    int64
 5   Target   830 non-null    int64
dtypes: int64(6)
memory usage: 39.0 KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
BI-RADS    830 non-null int64
Age        830 non-null int64
Shape      830 non-null int64
Margin     830 non-null int64
Density    830 non-null int64
Target     830 non-null int64
dtypes: int64(6)
memory usage: 39.0 KB

**Which type of cancer is common?**

In [ ]:
# Code here please
print(df['Target'].value_counts().rename('Target'))

Target
0    427
1    403
Name: Target, dtype: int64

0    427
1    403
Name: Target, dtype: int64

**Reproduce the output to show some statistics**

In [ ]:
# Code here please
df.describe()

          BI-RADS         Age       Shape      Margin     Density      Target
count  830.000000  830.000000  830.000000  830.000000  830.000000  830.000000
mean     4.393976   55.781928    2.781928    2.813253    2.915663    0.485542
std      1.888371   14.671782    1.242361    1.567175    0.350936    0.500092
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   46.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

          BI-RADS         Age       Shape      Margin     Density      Target
count  830.000000  830.000000  830.000000  830.000000  830.000000  830.000000
mean     4.393976   55.781928    2.781928    2.813253    2.915663    0.485542
std      1.888371   14.671782    1.242361    1.567175    0.350936    0.500092
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   46.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

** Do the Train Test Split** using test size 0.3

In [ ]:
# Code here please
X=df.drop('Target',axis=1)
X

     BI-RADS  Age  Shape  Margin  Density
0          5   67      3       5        3
1          5   58      4       5        3
2          4   28      1       1        3
3          5   57      1       5        3
4          5   76      1       4        3
..       ...  ...    ...     ...      ...
825        4   47      2       1        3
826        4   56      4       5        3
827        4   64      4       5        3
828        5   66      4       5        3
829        4   62      3       3        3

[830 rows x 5 columns]

In [ ]:
# Code here please
y=df['Target']
y

0      1
1      1
2      0
3      1
4      1
      ..
825    0
826    1
827    0
828    1
829    0
Name: Target, Length: 830, dtype: int64

In [ ]:
# Code here please
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Decision Tree
**Importing decision tree classifier and create its instance**

In [ ]:
# Code here please
from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier()

**Fit the training data to the model**

In [ ]:
# Code here please
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

**What is the Score of the model?**

In [ ]:
# Code here please
print(dtree.score(X_test, y_test))

0.751004016064257